xmlgen: Avoid double-free
As revealed by Coverity scan report:

https://bugzilla.redhat.com/show_bug.cgi?id=728245#c8
https://bugzilla.redhat.com/attachment.cgi?id=530435

Error: USE_AFTER_FREE:
xmlgen.c:1271: freed_arg: "free" frees "string".
xmlgen.c:1317: double_free: Calling "free" frees pointer "string" which has
                            already been freed.

Error: USE_AFTER_FREE:
xmlgen.c:1288: freed_arg: "free" frees "string".
xmlgen.c:1317: double_free: Calling "free" frees pointer "string" which has
                            already been freed.

Signed-off-by: Eduardo Lima (Etrunko) <eblima@br.ibm.com>